### PR TITLE
add ability for modular import

### PR DESCRIPTION
**Pull request by avriy**
Add ability for just use import MailCore in swift sources

### CODE REVIEW

**Comment by dinhviethoa** [comment]
Could you describe what you did with MailCore.h?
It sounds like you added it to a build, I'm not sure which one.

**Comment by avriy** [comment]
I added it to mailcore osx target and mailcore ios target as a public header

**Comment by dinhviethoa** [comment]
There was already a copy phase script that would copy the headers.
Does adding the headers in the header copy phase help with anything?
What happens if you remove the reference to this header?

**Comment by avriy** [comment]
I know it) Without the reference there is a warning in mailcore osx target: 
warning: no umbrella header found for target 'mailcore osx', module map will not be generated
and then "import MailCore" fails to find module with
No such module 'MailCore'

**Comment by dinhviethoa** [comment]
Sounds good. Thanks!

**Pull request merged**
