### PR TITLE
Add type annotations to some operations and MCPIMAPSession

### PR DESCRIPTION
**Pull request by Palleas**
Same as #1530 ! :shipit: 

See #1426.

### CODE REVIEW

**Comment by dinhviethoa** [comment]
It caused a build failure :(
https://travis-ci.org/MailCore/mailcore2/jobs/167513546

**Comment by Palleas** [comment]
It seems to be an issue related to C++..?

**Comment by Palleas** [comment]
It seems to be this part that fails on OSX. Do you want to restore `master` to a working state while I investigate ? It looks like type annotations doesn't play well with C++..? Could be a compiler version issue ? 🤔

**Comment by dinhviethoa** [comment]
I'I going to revert that commit. Did it at least work locally for you?

**Comment by Palleas** [comment]
Yeah it works in Xcode (8) but the issue happens in the CMake build and that I'm unable to run locally: https://github.com/MailCore/mailcore2/blob/master/scripts/travis/script.sh#L43-L49

**Comment by dinhviethoa** [comment]
Is it building for i386? Maybe it may be why it's failing?

**Comment by Palleas** [comment]
I'll try to build it locally but I miss some dependencies like `libetpan` so it may take some time. 

I also noticed that the build script still uses xctool and the travis build targets xcode 7. Is it ok if I open a PR for migrating to xcodebuild (or facebook new toy, xcbuild)?

**Comment by dinhviethoa** [comment]
Sure. You can open a PR to use xcodebuild or xcbuild.
xcbuild would probably be preferred since it's probably less verbose than xcodebuild.

**Comment by dinhviethoa** [comment]
I'm about to revert that commit. Could you give it a try to xcodebuild if it help?

**Comment by Palleas** [comment]
Instead of xcbuild you mean?

**Comment by dinhviethoa** [comment]
Yes. Then, switch to xcbuild later.

**Comment by Palleas** [comment]
I'll work on that then!

**Comment by Palleas** [comment]
(Just to be clear I'm still working on adding xcbuild as well but I haven't had much time lately 😊 )

**Comment by dinhviethoa** [comment]
Please resend the pull request when the switch to xcodebuild is ready!

**Pull request merged**
