### PR TITLE
Fix Operation Progress Listener

### LINKED ISSUE #1586: [Android] NoSuchFieldError excpetion when setProgressListener()
Operation.setProgressListener() will crash as
        //JNI DETECTED ERROR IN APPLICATION:
        // JNI GetObjectField called with pending exception java.lang.NoSuchFieldError:
        // no "J" field "listener" in class "Lcom/libmailcore/IMAPFetchMessagesOperation;" or its superclasses

Test code:

        final IMAPFetchMessagesOperation op = mImapSession.fetchMessagesByUIDOperation(folderPath, kind, indexSet);

        op.setProgressListener(new IMAPOperationItemProgressListener() {
            @Override
            public void itemProgress(long l, long l1) {
                progressCallback.progress(l, l);
            }
        });

### PR DESCRIPTION
**Pull request by farnabaz**
Its good to have progressListener on every IMAPOperationOperation, but its sad to see this feature is not functioning and using `setProgressListener` cause app crash
After digging inside mailcore2, Finally I could fix this issue
- First we need to add extra argument to `getObjectField` in order to specify field class (#1482)
- Then we need to create a global reference of listener and store global reference, because android garbage collector [moves objects around](https://android-developers.googleblog.com/2011/11/jni-local-reference-changes-in-ics.html), and local references may not valid 

Fix #1586

### CODE REVIEW

**Comment by 2h4u** [comment]
@farnabaz Hey, I just compiled a new .aar of the current master branch but unfortunately my android app still crashes as soon as I try to set a connection logger with the following error:

```
    JNI DETECTED ERROR IN APPLICATION: fid == null
    java_vm_ext.cc:542]     in call to GetObjectField
    java_vm_ext.cc:542]     from void com.libmailcore.IMAPSession.setupNativeConnectionLogger()
(...)
    thread.cc:2166] No pending exception expected: java.lang.NoSuchFieldError: no "J" field "connectionLogger" in class "Lcom/libmailcore/IMAPSession;" or its superclasses
    thread.cc:2166]   at void com.libmailcore.IMAPSession.setupNativeConnectionLogger() (IMAPSession.java:-2)
    thread.cc:2166]   at void com.libmailcore.IMAPSession.setConnectionLogger(com.libmailcore.ConnectionLogger) (IMAPSession.java:95)
```

I know it is a long time ago but can you remember how you compiled your .aar ? Like which NDK version, which SDK version, any modifications to the build.sh file and so on?

Any help would be greatly appreciated.

**Comment by farnabaz** [comment]
@2h4u Hey, Sorry for the late response. I was compiling this using my old laptop and as I remember it does not work with new NSK versions. I will check out NDK version and let you know

**Comment by 2h4u** [comment]
@farnabaz Hey thanks for replying 😄 
I was able to compile mailcore2 with this NDK: http://dl.google.com/android/repository/android-ndk-r10e-darwin-x86_64.zip
and the Android SDK with API level 16

Everything was working fine but as soon as I tried to set a connection logger I got the error I described in my first post (https://github.com/MailCore/mailcore2/pull/1787#issuecomment-712118626)

I thank you in advance for looking into this again

**Comment by farnabaz** [comment]
@2h4u Sorry, I don't remeber much about it. Have you look at https://github.com/MailCore/mailcore2/issues/1482? The main idea of this PR cames for this issue.

**Comment by 2h4u** [comment]
@farnabaz no worries 😄
yeah i had a look at the issue, then I saw your PR and thought that it might work if i compile the current master into an .aar but unfortunately the new .aar still crashed. Have you actually managed to set a connection logger with your self compiled .aar?

**Comment by farnabaz** [comment]
> If yes, would it be possible that you share the .aar with the community? I'm sure the community would appreciate it 😃

Gladly 🙂 

Here is the .aar that I used for my project.

https://drive.google.com/file/d/1giSDOqpm6dpJ5i1W-93mR76Y-7SKgUys/view?usp=sharing

The generation date was the exact date of this PR. Oct 5, 2018.

**Comment by 2h4u** [comment]
Thanks for sharing!
Unfortunately your .aar produces on my android app the same crash-error as soon as I try to set the connection logger `IMAPSession.setConnectionLogger()`:

```
 java_vm_ext.cc:570] JNI DETECTED ERROR IN APPLICATION: JNI GetObjectField called with pending exception java.lang.NoSuchFieldError: no "J" field "connectionLogger" in class "Lcom/libmailcore/IMAPSession;" or its superclasses
 java_vm_ext.cc:570]   at void com.libmailcore.IMAPSession.setupNativeConnectionLogger() (IMAPSession.java:-2)
 java_vm_ext.cc:570]   at void com.libmailcore.IMAPSession.setConnectionLogger(com.libmailcore.ConnectionLogger) (IMAPSession.java:95)
```

Did you manage to set the `connectionLogger` of the `IMAPSession` or did you just use the .aar to set the `progressListener ` ?

**Comment by farnabaz** [comment]
@2h4u If you are getting the same error that for sure I didn't use `connectionLogger` back then.

I was looking at changes of this PR and I just realized something that might help. Could you replace "J" with "Lcom/libmailcore/ConnectionLogger" in 
```
     jobject javaLogger = getObjectField(env, obj, "connectionLogger", "J"); 
```
and check the result. You can find files in cahnges tab

**Comment by 2h4u** [comment]
@farnabaz Thanks for the tipp! 
I will try it out next week and report back, thanks again and have a nice weekend! 🙂

**Comment by 2h4u** [comment]
@farnabaz I finally managed to try it out but unfortunately it still crashes, this time with the following error:

```
java_vm_ext.cc:570] JNI DETECTED ERROR IN APPLICATION: JNI GetObjectField called with pending exception java.lang.NoSuchFieldError: no type "Lcom/libmailcore/ConnectionLogger" found and so no field "connectionLogger" could be found in class "Lcom/libmailcore/IMAPSession;" or its superclasses
java_vm_ext.cc:570]   at void com.libmailcore.IMAPSession.setupNativeConnectionLogger() (IMAPSession.java:-2)
java_vm_ext.cc:570]   at void com.libmailcore.IMAPSession.setConnectionLogger(com.libmailcore.ConnectionLogger) (IMAPSession.java:95)
```

I tried to investigate the problem but my JNI skills are pretty much non existent, so I having a hard time to figure out the problem. Nevertheless, thank you for you time and effort!

**Pull request merged**
